---
- name: Check if AMI exists and create EC2 Instance
  hosts: localhost
  gather_facts: yes
  vars:
    region: us-east-1
    ami_id: ami-0aebec83a182ea7ea
    instance_type: t2.micro
    key_name: harsha-anna-aws-naga.pem
    security_group: sg-025b5a777086208b9
  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "test-instance-ansible"
#        key_name: "harsha-anna-aws-naga.pem"
#        vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        security_group: default
        network_interfaces:
          - assign_public_ip: true
        image_id: ami-012967cc5a8c9f891
        tags:
          Environment: Testing
      register: ec2
    - name: Output Instance Information
      debug:
        var: ec2.instances

#References:
#  https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_ami_module.html
#  https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_ami_info_module.html
#  https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_module.html